### ISSUE TITLE
Folder name ending with .js will show JS icon

### ISSUE THREAD

**Issue by julkue** [leviothan/atom-prime-file-icons#1]
When having a folder name ending with ".js" the default JavaScript icon will appear. I am expecting a folder icon like in any other project folder.

**Comment by leviothan** [comment]
@julmot thanks for the first issue.
fixed in 0.2.1

**Comment by julkue** [comment]
@leviothan Thanks. The issue was solved for subdirectories of a project but not for the project folder itself.

**Comment by leviothan** [comment]
fixed in 0.2.2
