### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by SomethingNew71** [leviothan/atom-prime-file-icons#2]
Do you have any plans to make Typescript supported?  I would love if my file icons included .ts

**Comment by leviothan** [comment]
Yes. Any suggestions for icon?  
Don't have much time now. But i will try to add .ts icon as soon as i can.

**Comment by SomethingNew71** [comment]
I think file icons the one you based this off of just uses **#294E80** color blue "ts" in **wf_segoe-ui_normal** font.

**Comment by leviothan** [comment]
Cant find my source svg icons. And don't know how to add new icon to existing woff font :/
.ts files now have same icon as .js but with another color.

**Comment by SomethingNew71** [comment]
No worries!  That will be great in the mean time.  Are you open to me trying to create a PR with an updated svg?

**Comment by leviothan** [comment]
Of course!

**Comment by SomethingNew71** [comment]
I am tried tackling this myself and let's just say I don't think I should quit my day job developing for design work.  Gonna go ahead and close this.
